FROM nvcr.io/nvidia/l4t-jetpack:r35.2.1
# FROM nvcr.io/nvidia/l4t-base:r36.2.0

RUN apt-get -y update

RUN apt-get -y install git cmake build-essential

RUN git clone https://github.com/dusty-nv/jetson-utils.git

RUN apt-get -y install software-properties-common

RUN add-apt-repository -y ppa:deadsnakes/ppa 

RUN apt-get -y install python2.7 python3.6 python3.7

RUN apt-get -y install libpython3-dev python3-numpy

RUN apt-get -y install libjson-glib-dev libgstreamer-plugins-base1.0-dev libsoup2.4-dev

WORKDIR /jetson-utils

RUN mkdir build

WORKDIR /jetson-utils/build

RUN cmake ../

RUN make

RUN make install

RUN ldconfig


